# configs/experiment_configs/realworld_deployment.yaml
_base_: 
  - ../model_configs/gemini_coopmil.yaml
  - ../optimization/hardware_optimization.yaml

deployment:
  environment: "production"
  scaling:
    min_replicas: 3
    max_replicas: 10
    autoscaling_metric: "requests_per_second"
    target_value: 100
  
  monitoring:
    dashboards:
      - name: "fairness_monitor"
        metrics: ["age_bias_score", "gender_parity"]
        refresh_interval: 60
      - name: "performance"
        metrics: ["latency_p99", "throughput"]
    
    alerting:
      thresholds:
        fairness_violation: 0.15
        latency_degradation: 30%
      notification_channels: ["slack#alerts", "pagerduty"]

  canary_release:
    stages:
      - percentage: 5%
        duration: 1h
        validation_metrics:
          accuracy: 0.85
          fairness: 0.9
      - percentage: 25%
        duration: 4h
      - percentage: 100%
